initial fixes on balancing issues
JoshuaJB/litmus-rt pull request #4
Opened 2020-09-29 00:33 UTC by leochanj105

Leo's initial fixes on balancing issues:

I tried to add the check is_realtime(rq->curr) in pick_next_task_litmus(), and it seemed to work properly with no uses of prev in the function. I'll definitely run more extensive test cases to complete the updates.

2020-09-29 19:03 UTC, JoshuaJB requested changes
There's just one substantive change that I'd like you to look into, otherwise I only have a couple minor nitpicks (abbreviated nit).

2020-09-29 19:03 UTC, JoshuaJB commented on kernel/sched/litmus.c
> +		update_time_litmus(rq, rq->curr);
Nit: It looks like you moved these down a line from before. Removing the preceding newline and adding one after should make the diff a bit cleaner.

2020-09-29 19:03 UTC, JoshuaJB commented on kernel/sched/litmus.c
When `is_realtime(rq->curr)` is true in your tests, `put_prev_task()` should call `litmus_put_prev_task()`. Because of that, I think you're just calling `put_prev_task()` in the case that it's a no-op. If that's true, you should just be able to remove these lines (and the preceding comment).

2020-09-29 19:03 UTC, JoshuaJB commented on kernel/sched/litmus.c
> +balance_litmus(struct rq *rq, struct task_struct *prev, struct rq_flags *rf){
Nit: The rest of this file likes to use the style where the opening curly bracket is on the line after the function signature.

2020-09-30 04:31 UTC, leochanj105 commented
I tried the assumptions and it worked properly (for now). I will run more tests to make it more robust.
Also, the style problems are fixed.

2020-09-30 04:36 UTC, JoshuaJB approved these changes
Looks great! I'll merge it shortly.

2020-09-30 04:42 UTC, merged